"""Search metadata for Candlewise tools.

This metadata is intentionally separate from the model-facing JSON schemas.
The runtime can use it for discovery, while the host still owns executable
tool registration and permission decisions.
"""

from pan_agent import ToolRisk
from pan_agent_tool_research import ToolDataFreshness, ToolDescriptor


CANDLEWISE_TOOL_DESCRIPTORS: tuple[ToolDescriptor, ...] = (
    ToolDescriptor(
        tool_name="get_portfolio",
        title="Get holdings",
        summary="Get the user's real and simulation holdings, position sizes and a portfolio summary.",
        use_cases=["analyse my holdings", "view my portfolio", "check portfolio risk"],
        keywords=["holdings", "portfolio", "positions", "account", "investments"],
        aliases=["my stocks", "what do I hold", "show my holdings"],
        domain="portfolio",
        capabilities=["portfolio_read", "risk_analysis"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=500,
        output_summary="Holdings summary and risk data.",
    ),
    ToolDescriptor(
        tool_name="get_stock_quote",
        title="Get live quote",
        summary="Get a stock's latest price, change % and intraday data.",
        use_cases=["check a share price", "view a live quote", "see the current price"],
        keywords=["quote", "share price", "price", "ltp", "change", "live"],
        aliases=["stock price", "latest price", "how much is the stock now"],
        entities=["stock symbol", "market"],
        domain="market_data",
        capabilities=["quote", "market_data"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=1_000,
        output_summary="Latest price, change % and trading status.",
    ),
    ToolDescriptor(
        tool_name="find_research_candidates",
        title="Find research candidates",
        summary="Screen the market and your holdings for stocks worth researching further, with their signals.",
        use_cases=["find ideas to research", "screen stocks", "look for research candidates"],
        keywords=["ideas", "candidates", "research", "screener", "screen", "signals"],
        aliases=["find ideas", "stocks to look at", "research candidates"],
        domain="investment_research",
        capabilities=["candidate_discovery", "signal_screening", "research"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=3_000,
        output_summary="Candidates, scores, risks and levels.",
    ),
    ToolDescriptor(
        tool_name="get_kline_summary",
        title="Analyse the K-line trend",
        summary="Get a summary of a stock's moving averages, momentum and recent K-line indicators.",
        use_cases=["analyse technicals", "check the trend", "find support and resistance"],
        keywords=["kline", "candles", "technical analysis", "moving average", "trend", "momentum", "support", "resistance"],
        aliases=["chart", "technicals", "price action"],
        domain="market_data",
        capabilities=["technical_analysis", "kline", "trend_analysis"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=1_500,
        output_summary="K-line indicators, trend, support and resistance summary.",
    ),
    ToolDescriptor(
        tool_name="get_stock_news",
        title="Search stock news",
        summary="Search a stock's news, corporate announcements and updates from the last seven days.",
        use_cases=["find stock news", "see company updates", "check the latest announcements"],
        keywords=["news", "headlines", "updates", "announcements", "sentiment"],
        aliases=["any recent news", "latest announcements", "what's new"],
        domain="market_data",
        capabilities=["news", "event_research", "sentiment"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="Recent headlines, sources and summaries.",
    ),
    ToolDescriptor(
        tool_name="search_stocks",
        title="Search stocks",
        summary="Search the stock list by symbol or name to confirm a symbol and market.",
        use_cases=["search for a stock", "find a stock symbol", "confirm a company name"],
        keywords=["search stock", "stock symbol", "company name", "ticker", "find symbol"],
        aliases=["find a stock", "look up a stock", "what is the symbol for"],
        entities=["stock symbol", "company name", "market"],
        domain="market_data",
        capabilities=["symbol_search", "instrument_lookup"],
        data_freshness=ToolDataFreshness.STATIC,
        estimated_latency_ms=1_000,
        output_summary="Matching stock symbols, names and markets.",
    ),
    ToolDescriptor(
        tool_name="get_market_status",
        title="Get market status",
        summary="Get the current trading status and session times of the Indian market (NSE/BSE).",
        use_cases=["is the market open", "check trading hours", "can I trade now"],
        keywords=["market open", "market close", "trading hours", "trading status", "market status"],
        aliases=["is the market open now", "is it a trading day today", "has the market opened"],
        domain="market_data",
        capabilities=["market_status", "trading_calendar"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=100,
        output_summary="Trading status, time zone and session times.",
    ),
    ToolDescriptor(
        tool_name="get_price_alerts",
        title="List price alerts",
        summary="List the user's price alerts, their conditions and whether they are on.",
        use_cases=["view alerts", "list price alerts", "see what's being watched"],
        keywords=["alert", "price alert", "alerts", "monitor", "trigger condition"],
        aliases=["my alerts", "which price alerts do I have"],
        domain="price_alerts",
        capabilities=["alert_read", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=300,
        output_summary="Alert ID, stock, condition and status.",
    ),
    ToolDescriptor(
        tool_name="update_price_alert",
        title="Update price alert",
        summary="Change a price alert's target price, direction or on/off state.",
        use_cases=["change an alert", "adjust an alert price", "turn off a price alert"],
        keywords=["update alert", "change alert", "edit price alert"],
        aliases=["edit alert", "change the alert condition"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["changes a user price alert"],
    ),
    ToolDescriptor(
        tool_name="delete_price_alert",
        title="Delete price alert",
        summary="Delete a price alert and its trigger history.",
        use_cases=["delete an alert", "cancel a price alert", "clean up alerts"],
        keywords=["delete alert", "cancel alert", "remove alert"],
        aliases=["remove the alert", "I don't need this alert"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["deletes a user price alert"],
    ),
    ToolDescriptor(
        tool_name="create_price_alert",
        title="Create price alert",
        summary="Create an intraday price alert for a stock already in the app.",
        use_cases=["set a price alert", "create a price alert", "watch for a breakout or breakdown"],
        keywords=["create alert", "set alert", "price alert", "breakout", "breakdown"],
        aliases=["alert me", "set a price alert"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["creates a user price alert"],
    ),
)
