markets:
  - code: IN
    stocks:
      - symbol: "INFY"
        name: "Infosys"
        # cost_price: 1500.00
        # quantity: 10
      - symbol: "HDFCBANK"
        name: "HDFC Bank"
      - symbol: "RELIANCE"
        name: "Reliance Industries"
